name: /home/iamamoron/rajeev/work/learn/condata/scikitlrn/.env
channels:
  - conda-forge
  - defaults
dependencies:
  # python
  - python=3.12

  - streamlit
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - xgboost
  - joblib
  - ipykernel
  - pip
